<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKx8l6lf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKx8l6lf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKx8l6lf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKx8l6lf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKx8l6lf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kx8l6lf',
    'container.build_id' => '5f38a6b0',
    'container.build_time' => 1539290946,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKx8l6lf');
