<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTmxi8fi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTmxi8fi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTmxi8fi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTmxi8fi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTmxi8fi\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Tmxi8fi',
    'container.build_id' => '76b2cc02',
    'container.build_time' => 1536605757,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTmxi8fi');
